### ISSUE TITLE
Parameter token or opts.auth is required

### ISSUE THREAD

**Issue by niinpatel** [getsentry/action-eslint-fix#16]
Getting the following error when running the action. Any idea what's missing? 

```
Run getsentry/action-eslint-fix@019e40047bc28cbe8c2c12073d37365737182ad4
  with:
    dry: false
  env:
    GITHUB_TOKEN: ***
Error: Parameter token or opts.auth is required
```

code - 
```
name: Automatic Lint Fixes
on:
  issue_comment:
    types:
      - created
jobs:
  eslint:
    name: eslint
    if: github.event.issue.pull_request && github.event.comment.body == '/eslint'
    runs-on: ubuntu-20.04
    steps:
      - name: Automatic Lint Fix
        uses: getsentry/action-eslint-fix@019e40047bc28cbe8c2c12073d37365737182ad4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

**Comment by niinpatel** [comment]
resolved - 
token needs to be passed as param instead of env
```
    steps:
      - name: Automatic Lint Fix
        uses: getsentry/action-eslint-fix@019e40047bc28cbe8c2c12073d37365737182ad4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
