### ISSUE TITLE
Action doesn't commit fixes

### ISSUE THREAD

**Issue by beazt123** [getsentry/action-eslint-fix#19]
### Environment
`ubuntu-latest`

How do you use Sentry? No
Sentry SaaS (sentry.io) or self-hosted/on-premise (which version?)

Which SDK and version?
e.g: JavaScript 5.11.1, .NET 1.2.0

### Steps to Reproduce

1. Prepare a small Vue-Typscript project scaffold. Mine's [here](https://github.com/beazt123/eslint-test-app)
2. Create a few javascript functions. Put extra semicolons in some code to trigger an automatic fix by eslint.
3. Create a github action like below. Mine's [here](https://github.com/beazt123/eslint-test-app/blob/feature/.github/workflows/lint.yml):
```yml
  lintFix:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm install
    - name: Use current action
      uses: getsentry/action-eslint-fix@v1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

### Expected Result
`"style(): Auto eslint fix"` to appear in the commit history for my PR

### Actual Result
None

What actually happened. Maybe a screenshot/recording? Maybe some logs?
No error. Everything went smoothly in the logs
